name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and without
        run: mvn clean package -DskipTests

      - name: Deploy the application
        uses: appleboy/scp-action@master
        with:
          host: kino.avada-media-dev1.od.ua
          username: avada_kino
          password: ${{ secrets.TOMCAT_PASSWORD }}
          source: target/*.war
          target: /home/avada/web/kino.avada-media-dev1.od.ua/tomcat/webapps
          strip_components: 1

#123